[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true

[opener]
edit = [
  { run = "${EDITOR:-vi} %s", desc = "Editor", for = "unix", block = true },
]
play = [
  { run = "xdg-open %s1", desc = "Play", for = "linux", orphan = true },
  { run = "open %s", desc = "Play", for = "macos" },
  { run = "mediainfo %s1 | less", block = true, desc = "Show media info", for = "unix" },
]
open = [
  { run = "xdg-open %s1", desc = "Open", for = "linux" },
  { run = "open %s", desc = "Open", for = "macos" },
]
folder = [
  { run = "dolphin %d1", desc = "Reveal", for = "linux" },
  { run = "open -R %s1", desc = "Reveal", for = "macos" },
]
reveal = [
  { run = "dolphin %d1", desc = "Reveal", for = "linux" },
  { run = "open -R %s1", desc = "Reveal", for = "macos" },
  { run = "clear; exiftool %s1 | less", desc = "Show EXIF", for = "unix", block = true },
]
extract = [{ run = 'ouch d -y "$@"', desc = "Extract here", for = "unix" }]
download = [
  { run = "ya emit download --open %S", desc = "Download and open" },
  { run = "ya emit download %S", desc = "Download" },
]
execute = [{
  run = "kitty -e %s", desc = "Run"
}]

[open]
rules = [
  # Folder
  { url = "*/", use = [
    "folder",
    "reveal",
  ] },
  # Text
  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  # Image
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  # Media
  { mime = "{audio,video}/*", use = [
    "play",
    "reveal",
  ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
    "extract",
    "reveal",
  ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },
  # Empty file
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },
  # Virtual file system
  { mime = "vfs/{absent,stale}", use = "download" },
  # Fallback
  { url = "*", use = [
    "open",
    "reveal",
    "edit",
    "execute",
  ] },
]


# Git plugin
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"
[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
