# Remap Prefix
set -g prefix C-space
unbind C-b
bind C-space send-prefix

# Reload configuration
bind C-o source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

#  ━━━━━━━━━ Copy mode ━━━━━━━━━
bind Enter copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind -T copy-mode-vi [ send-keys -X previous-prompt -o
bind -T copy-mode-vi ] send-keys -X next-prompt -o
#  ━━━━━━━━━ Sessions ━━━━━━━━━
bind Q kill-session
bind C-n command-prompt -I "#{session_name}" "rename-session '%%'"
#  ━━━━━━━━━ Windows ━━━━━━━━━
bind q kill-window
bind t new-window -c "#{pane_current_path}"
bind -r ] next-window
bind -r [ previous-window
bind n command-prompt -I "#W" "rename-window '%%'"
bind a last-window
#  ━━━━━━━━━ Panes ━━━━━━━━━
bind C-q kill-pane
bind "\\" split-window -fh -c "#{pane_current_path}" # -f ensures that the vertical split will use full height and not split
bind - split-window -v -c "#{pane_current_path}"
bind > swap-pane -D
bind < swap-pane -U
bind f resize-pane -Z
bind v if -F '#{==:#{pane_width},#{window_width}}' 'select-layout even-horizontal' 'select-layout even-vertical'
