set -s set-clipboard on
#  ━━━━━━━━━ Global Options ━━━━━━━━━
set -g mouse on             # Enable mouse
set -g history-limit 50000  # Scrollback buffer
set -g display-time 2000    # Status message display time
set -g status-interval 5    # Status poll
set -g status-keys emacs    # emacs keybind in command prompt
set -g set-titles on
set -g focus-events on
set -g allow-passthrough on
set -g base-index 1
set -g renumber-windows on  # Renumember windows after closing

#  ━━━━━━━━━ Window/Pane Options ━━━━━━━━━
setw -g pane-base-index 1
setw -g aggressive-resize on # resize the window to the size of the smallest or largest session
setw -g mode-keys vi         # Set vi keybinds to copy mode

# # Theming and layout
# set -g default-terminal "${TERM}"
# set -g status-position bottom
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
# # Environment
# set-environment -g TMUX_DATA_DIR "${HOME}/.local/share/tmux"
#
# # Ohers
set -g status-justify left
set -g status-style "bg=default,fg=#e2d9c5"
set -g status-left-length 30
set -g status-left "#[fg=#06101e,bg=#fd5e3a,bold] #S #[bg=default,nobold] "
set -g status-right "#{?client_prefix,#[fg=#fd5e3a bold]● PREFIX ,}#[fg=#66def9]#h "
set -g window-status-format "#[fg=#3e7a9b] #I #W "
set -g window-status-current-format "#[fg=#06101e,bg=#66def9,bold] #I #W#{?window_zoomed_flag, [Z],} #[bg=default,nobold]"
set -g window-status-separator ""
set -g pane-border-style "fg=#052839"
set -g pane-active-border-style "fg=#35b5ff"
set -g message-style "bg=default,fg=#66def9"
set -g mode-style "bg=#08435E,fg=#e2d9c5"
