set -s set-clipboard on
#  ━━━━━━━━━ Global Options ━━━━━━━━━
set -g mouse on             # Enable mouse
set -g history-limit 50000  # Scrollback buffer
set -g display-time 2000    # Status message display time
set -g status-interval 5    # Status poll
set -g status-keys emacs    # emacs keybind in command prompt
set -g set-titles on
set -g focus-events on
set -g allow-passthrough on
set -g base-index 1
set -g renumber-windows on  # Renumember windows after closing

#  ━━━━━━━━━ Window/Pane Options ━━━━━━━━━
setw -g pane-base-index 1
setw -g aggressive-resize on # resize the window to the size of the smallest or largest session
setw -g mode-keys vi         # Set vi keybinds to copy mode

# # Theming and layout
# set -g default-terminal "${TERM}"
# set -g status-position bottom
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
# # Environment
# set-environment -g TMUX_DATA_DIR "${HOME}/.local/share/tmux"
#
# # Ohers
