set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-yank'

#  ━━━━━━━━━ Plugin Options ━━━━━━━━━
## smart-splits
set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)

set -g @smart-splits_move_left_key  'C-h' # key-mapping for navigation.
set -g @smart-splits_move_down_key  'C-j' #  --"--
set -g @smart-splits_move_up_key    'C-k' #  --"--
set -g @smart-splits_move_right_key 'C-l' #  --"--

set -g @smart-splits_resize_left_key  'C-Left' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'C-Down' #  --"--
set -g @smart-splits_resize_up_key    'C-Up' #  --"--
set -g @smart-splits_resize_right_key 'C-Right' #  --"--

set -g @smart-splits_resize_step_size '3' # change the step-size for resizing.
