# Apps that should be start as soon as hyperland stars
# Daemons and others related should go in execs

exec-once = [workspace 7 silent] proton-mail
exec-once = [workspace 8 silent] betterbird
exec-once = [workspace 7 silent] keepassxc
