decoration {
    rounding = 15
    rounding_power = 2

    active_opacity = 1
    inactive_opacity = 1

    blur {
        enabled = yes
        size = 3
        passes = 4
        ignore_opacity = true
        vibrancy = 0.1696
        new_optimizations = true
        xray = true
        noise = 0.0
        popups = true
    }

    shadow {
      enabled = no
      range = 30
      scale = 2
      render_power = 5
      color = rgba(1a1a1aee)
    }

    dim_inactive = false
    dim_strength = 0.05
}
