# This file contains the default application that have
# binds to be launched

$applauncher = vicinae toggle
$terminal = kitty
$mainBrowser = firefox
$offBrowser = chromium
$editor = kitty nvim
$filemanager = kitty -e fish -c "y; exec fish"
$g_filemanager = dolphin


# vicinae extensions launcher
$launcher-clipboard = vicinae vicinae://extensions/vicinae/clipboard/history
$launcher-emojis = vicinae vicinae://extensions/vicinae/core/search-emojis
$launcher-translator = vicinae vicinae://extensions/gebeto/translate/translate-form
$launcher-bookmarks = vicinae vicinae://extensions/aurelleb/chromium-bookmarks/search-bookmarks
