# This file contains the default application that have
# binds to be launched

$applauncher = ~/.config/rofi/scripts/launcher_t1
$terminal = kitty
$mainBrowser = firefox
$offBrowser = chromium
$editor = kitty nvim
$filemanager = kitty -e fish -c "y; exec fish"
$g_filemanager = dolphin
$powermenu = ~/.config/rofi/scripts/powermenu_t2


# vicinae extensions launcher
$launcher-clipboard = vicinae vicinae://extensions/vicinae/clipboard/history
$launcher-emojis = vicinae vicinae://extensions/vicinae/core/search-emojis
$launcher-translator = vicinae vicinae://extensions/gebeto/translate/translate-form
$launcher-bookmarks = vicinae vicinae://extensions/aurelleb/chromium-bookmarks/search-bookmarks
