# Window and workspaces rules

$priMon = DP-2
$secMon = DP-1


########################
### WORKSPACES RULES ###
########################
workspace = 1, monitor:$priMon, default:true
workspace = 3, monitor:$priMon
workspace = 5, monitor:$priMon
workspace = 7, monitor:$priMon

workspace = 2, monitor:$secMon, default:true
workspace = 4, monitor:$secMon
workspace = 6, monitor:$secMon
workspace = 8, monitor:$secMon


####################
### WINDOW RULES ###
####################
# Disable blur for xwayland context menus
windowrule = match:class ^()$, match:title ^()$, no_blur on

# Disable blur for every window
windowrule = match:class .*, no_blur on

## Allowed Blur
windowrule = match:class kitty, no_blur off

## Picture-in-Picture
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, keep_aspect_ratio on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, move (monitor_w*.73) (monitor_h*.72)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, size (monitor_w*.25) (monitor_h*.25)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, pin on

## Some applications specific
windowrule = match:class kitty, float on, size (monitor_w*.50) (monitor_h*.50), center on
windowrule = match:class org.kde.dolphin, float on, size (monitor_w*.50) (monitor_h*.50), center on

###################
### LAYER RULES ###
###################
layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

# disable animations for vicinae only
layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}
